(function(_ds){var window=this;var Z5=function(a){const b=a.Mk;let c='<div class="dropdown-tabbed-menu"><ul class="dropdown-tabbed-menu-list">';a=a.columns;const d=a.length;for(let e=0;e<d;e++){const f=a[e];c+='<li class="dropdown-tabbed-menu-list-item"><a href="#" column-id="'+_ds.Y(f.aq)+'" tabindex="0" track-type="nav" track-name="'+_ds.Y(f.text)+'" track-metadata-eventdetail="#" track-metadata-position="nav - '+_ds.Y(b)+'" track-metadata-module="secondary nav">'+_ds.U(f.text)+"</a></li>"}return(0,_ds.T)(c+"</ul></div>")},$5=
function(a){const b=a.Mk,c=a.href;a=a.text;return(0,_ds.T)('<div class="dropdown-tabbed-menu-button"><a href="'+_ds.Y(_ds.Z(c))+'" track-type="nav" track-name="'+_ds.Y(a)+'" track-metadata-eventdetail="'+_ds.Y(c)+'" track-metadata-position="nav - '+_ds.Y(b)+'" track-metadata-module="secondary nav">'+_ds.U(a)+"</a></div>")};var a6=function(a){a.bc=Array.from(a.querySelectorAll("tab"));let b=a.querySelector(".devsite-tabs-wrapper");if(!b){b=a.ownerDocument.createElement("div");b.classList.add("devsite-tabs-wrapper");a.appendChild(b);var c;null==(c=a.bc)||c.forEach(e=>{let f;return null==(f=b)?void 0:f.appendChild(e)})}a.v=b;a.appendChild(b);if(!a.hasAttribute("no-overflow")){c=a.ownerDocument.createElement("tab");_ds.C(a,"overflow-tab","",c);var d=a.ownerDocument.createElement("a");_ds.Gh(d,"#");d.textContent="M\u00e1s";
d.classList.add("devsite-icon");d.classList.add("devsite-icon-arrow-drop-down");c.appendChild(d);a.h=c;d=a.ownerDocument.createElement("div");d.classList.add("devsite-tabs-overflow-menu");_ds.C(a,"scrollbars","",d);_ds.C(a,"hidden","",d);a.D=d;c.appendChild(d);b.appendChild(c)}},e6=function(a){let b;null==(b=a.bc)||b.forEach(async(c,d)=>{if(await b6(c)){var e=Array.from(c.querySelectorAll(".devsite-tabs-dropdown-column")),f=c.querySelector(".devsite-tabs-dropdown"),g=c.querySelector("a");e.forEach((h,
k)=>{_ds.C(a,"column-id",`tab-${d}-column-${k}`,h)});e=e.map(h=>{const k=h.querySelector(".devsite-nav-title")||h.querySelector(".devsite-nav-item-title");return{aq:h.getAttribute("column-id"),text:null==k?void 0:k.textContent}});g&&(g=_ds.N(Z5,{Mk:(g.textContent||"").toLowerCase().trim(),columns:e}),f&&(e=c.querySelector(".devsite-tabs-dropdown-content")))&&(f.insertBefore(g,e),f=c.querySelector(".dropdown-tabbed-menu a"),c6(c),a.eventHandler.listen(g,"click",h=>{h.preventDefault();const k=c.querySelector(".dropdown-tabbed-menu-button");
h=h.target;k&&h.tagName&&"a"===h.tagName.toLowerCase()&&!k.contains(h)&&d6(a,c,(null==h?void 0:h.getAttribute("column-id"))||"")}),f&&d6(a,c,f.getAttribute("column-id")||""))}})},f6=function(a,b){if(!b)return 0;const c=[];let d=b;for(;d.parentElement&&0===d.offsetWidth;)c.push(d),_ds.C(a,"render-hidden","",d),d=d.parentElement;a=_ds.ul(b).width;for(const e of c)e.removeAttribute("render-hidden");return a},n6=function(a){a.eventHandler.listen(document.body,"devsite-sticky-resize",()=>a.G.Aa());a.eventHandler.listen(a,
"click",c=>{if(!(c.shiftKey||c.ctrlKey||c.metaKey||c.altKey)){var d=c.target,e=a.C(d);if(e)if(e===a.h)g6(a,c);else if(h6(a),d.classList.contains("devsite-tabs-dropdown-toggle"))c.preventDefault(),c.stopPropagation(),e.hasAttribute("dropdown--open")?i6(a):j6(a,e);else{var f;"A"===d.tagName?f=d:f=_ds.Ki(d,"A");var g=e.querySelector(".devsite-tabs-dropdown");g&&g.contains(d)?f&&f.hasAttribute("href")||(c.preventDefault(),c.stopPropagation()):(a.K(e),f&&f&&"#"!==f.href||a.G.Aa())}}});if(a.querySelector("tab[dropdown]")||
a.querySelector("tab[overflow-tab]")){var b="onpointermove"in window?"pointerover":"mouseover";const c="onpointermove"in window?"pointerleave":"mouseleave",d=a.querySelectorAll("tab[clickable]");if(d.length){for(const e of d)a.eventHandler.listen(e,"click",f=>{const g=f.target,h=a.C(g),k=null==h?void 0:h.querySelector(".devsite-tabs-dropdown");if(k){let l;(null==(l=a.h)?0:l.contains(g))||k.contains(g)||(f.preventDefault(),f.stopPropagation(),(null==h?0:h.hasAttribute("dropdown--open"))?i6(a):k6(a,
f))}});a.eventHandler.listen(document.body,"click",e=>{a.v&&!a.v.contains(e.target)&&i6(a)})}else a.eventHandler.listen(a,b,e=>void l6(a,e)),a.eventHandler.listen(a,c,()=>void m6(a))}b=[...a.querySelectorAll(".devsite-tabs-close-button")];for(const c of b)a.eventHandler.listen(c,"click",()=>i6(a))},o6=function(a){_ds.C(a,"hidden","",a.h);if(!(a.bc&&3>a.bc.length)){var b=f6(a,a);if(0!==b){var c,d=(null==(c=a.bc)?void 0:c.slice())||[],e=0,f;d.forEach(k=>{k.parentNode!==a.v&&(f?f.parentNode&&f.parentNode.insertBefore(k,
f.nextSibling):_ds.si(a.v,k,0));f=k;e+=f6(a,k)});if(!(e<=b)){c=a.M;var g;null==(g=a.h)||g.removeAttribute("hidden");(g=a.querySelector("[active]"))&&(c+=f6(a,g));for(var h;null==(h=d)?0:h.length;){const k=d.shift();if(k===g)continue;const l=f6(a,k||null);if(c+l<=b)c+=l;else{let m;null==(m=a.D)||m.appendChild(k)}}}}}},l6=async function(a,b){(await _ds.v()).isTouchEnabled()||k6(a,b)},m6=async function(a){(await _ds.v()).isTouchEnabled()||i6(a,300)},i6=function(a,b=0){_ds.H(a.j);window.clearTimeout(a.F);
const c=a.querySelector("tab[dropdown--open]");if(c){const d=c.querySelector(".devsite-tabs-dropdown");_ds.C(a,"dropdown-transition","",d);_ds.cl(a.j,d,_ds.Gf,()=>{null==d||d.removeAttribute("dropdown-transition");a.removeAttribute("dropdown--open");_ds.C(a,"hidden","",d)});a.F=window.setTimeout(()=>{c.removeAttribute("dropdown--open");p6(a,c)},b)}else a.removeAttribute("dropdown--open");h6(a)},k6=function(a,b){const c=b.target,d=a.C(c);if(d){let e;d===a.h||(null==(e=a.h)?0:e.contains(c))?g6(a,b):
j6(a,d)}},g6=async function(a,b){b.preventDefault();b.stopPropagation();document.body.dispatchEvent(new CustomEvent("devsite-close-overflow-tabs"));await _ds.Mj();if(!a.hasAttribute("overflow-menu--open")){b=await _ds.v();await b.whenReady();if(b.isTouchEnabled()){const d=e=>{a.contains(e.target)||h6(a);_ds.dl(a.j,document.body,["devsite-close-overflow-tabs","click"],d)};a.j.listen(document.body,["devsite-close-overflow-tabs","click"],d)}var c;null==(c=a.D)||c.removeAttribute("hidden");_ds.C(a,"overflow-menu--open",
"")}},j6=async function(a,b){h6(a);if(b.hasAttribute("dropdown")){if(_ds.H(a.j),window.clearTimeout(a.F),!b.hasAttribute("dropdown--open")){(await _ds.v()).isTouchEnabled()&&_ds.cl(a.j,document.body,"click",g=>{a.contains(g.target)||i6(a)});var c=a.querySelector("tab[dropdown--open]"),d=b.querySelector(".devsite-tabs-dropdown");if(d){d.removeAttribute("hidden");_ds.il(d,"left","");var e=_ds.hi(window||window),f=Array.from(d.querySelectorAll(".devsite-tabs-dropdown-column"));if(!b.hasAttribute("dropdown-full")&&
1<f.length){const g=[];f.forEach(k=>{g.push(k.scrollWidth)});const h=Math.max.apply(null,g);h*f.length<e.width?f.forEach(k=>{_ds.il(k,"width",`${h}px`)}):_ds.C(a,"dropdown-full","",b)}f=d.getBoundingClientRect();b.hasAttribute("dropdown-full")?_ds.il(d,"left",`-${f.left}px`):(e=Math.min(f.left,f.left+f.width-e.width),0<e&&_ds.il(d,"left",`-${e}px`));c?(c.removeAttribute("dropdown--open"),p6(a,c),c=c.querySelector(".devsite-tabs-dropdown"),null==c||c.removeAttribute("dropdown-transition"),_ds.C(a,
"hidden","",c)):(_ds.C(a,"dropdown-transition","",d),_ds.cl(a.j,d,_ds.Gf,()=>d.removeAttribute("dropdown-transition")));window.requestAnimationFrame(()=>{_ds.C(a,"dropdown--open","");_ds.C(a,"dropdown--open","",b);p6(a,b)})}else c&&(c.removeAttribute("dropdown--open"),p6(a,c))}}else i6(a)},p6=function(a,b){_ds.C(a,"aria-expanded",`${b.hasAttribute("dropdown--open")}`,b.querySelector(".devsite-tabs-dropdown-toggle"))},h6=function(a){_ds.C(a,"hidden","",a.D);a.removeAttribute("overflow-menu--open")},
b6=async function(a){return(await _ds.v()).isTouchEnabled()||!a.hasAttribute("generated-tab-menu")?!1:!0},c6=function(a){var b=a.querySelector(".dropdown-tabbed-menu-button-target");if(!a.querySelector(".dropdown-tabbed-menu-button")&&b){var c=a.querySelector("a");c&&(c=c.textContent,b=b.querySelector(".devsite-nav-item a"),a=a.querySelector(".dropdown-tabbed-menu"),b&&(c=_ds.N($5,{Mk:(c||"").toLowerCase().trim(),href:b.getAttribute("href")||"",text:b.textContent||""}),null==a||a.appendChild(c)))}},
d6=function(a,b,c){var d=Array.from(b.querySelectorAll(".devsite-tabs-dropdown-column"));b=Array.from(b.querySelectorAll(".dropdown-tabbed-menu a"));b.forEach(e=>e.removeAttribute("active"));d.forEach(e=>_ds.C(a,"hidden","",e));b=b.find(e=>e.getAttribute("column-id")===c);d=d.find(e=>e.getAttribute("column-id")===c);b&&d&&(_ds.C(a,"active","",b),d.removeAttribute("hidden"))},q6=class extends _ds.E{constructor(){super();this.eventHandler=new _ds.G;this.j=new _ds.G;this.G=new _ds.Zk(()=>{o6(this)},
20);this.J=null;this.H=!1;this.F=0;this.D=this.h=null;this.M=0;this.bc=[];this.v=null;_ds.qh(this,this.o`active`,this.o`aria-expanded`,this.o`aria-selected`,this.o`collapsed`,this.o`column-id`,this.o`connected`,this.o`dropdown`,this.o`dropdown-full`,this.o`dropdown--open`,this.o`dropdown-transition`,this.o`hidden`,this.o`no-overflow`,this.o`overflow-menu--open`,this.o`overflow-tab`,this.o`render-hidden`,this.o`scrollbars`)}disconnectedCallback(){_ds.H(this.eventHandler);_ds.H(this.j)}connectedCallback(){this.H||
(a6(this),this.H=!0);_ds.C(this,"connected","");if(!this.hasAttribute("no-overflow")){_ds.C(this,"collapsed","",this.h);this.M=f6(this,this.h);var a;null==(a=this.h)||a.removeAttribute("collapsed");n6(this);o6(this)}e6(this)}C(a){for(;a&&a!==this;){if("TAB"===a.tagName.toUpperCase())return a;a=a.parentElement}return null}K(a){const b=this.J||this.querySelector("[active]");b&&(b.removeAttribute("active"),_ds.C(this,"aria-selected","false",b));_ds.C(this,"active","",a);_ds.C(this,"aria-selected","true",
a);this.J=a}};q6.prototype.connectedCallback=q6.prototype.connectedCallback;q6.prototype.disconnectedCallback=q6.prototype.disconnectedCallback;try{window.customElements.define("devsite-tabs",q6)}catch(a){console.warn("devsite.app.customElement.DevsiteTabs",a)};})(_ds_www);
