(function(_ds){var window=this;var vU=function(a){return!a.classList.contains("material-icons")},DU=async function(a,b){await DevsiteApp.whenReady();const c=_ds.F();var d=DevsiteApp.getInsecureHost();b=b.ma;if(b.origin===c.origin||!d||b.origin===d){try{var e=_ds.tf(_ds.Yl,b.data)}catch(g){return}d=_ds.pf(e,1);if(4===d)wU(a,b);else{var f=e.getName();if(f&&(f=a.querySelector(`devsite-iframe iframe[name="${f}"]`)))switch(d){case 5:xU(e,f);break;case 8:yU(b,e,c);break;case 1:zU(b,e,c);break;case 6:case 7:AU(d,c,e);break;case 9:BU(a,
e);break;case 10:CU(e,c)}}}},HU=function(a){a.v=a.querySelector(".devsite-article-body");a.v&&(EU(a),a.C=[]);a.h&&a.h.disconnect();a.j.clear();FU(a);if(!document.body.hasAttribute("appearance")){var b=[...a.querySelectorAll("picture > source.devsite-dark-theme")];for(var c of b){b=c.closest("picture");const d=b.querySelector("img");b.querySelectorAll("source:not(.devsite-dark-theme)").length?c.remove():b&&d&&b.replaceWith(d)}}c=Array.from(a.querySelectorAll(".devsite-nav-title, .devsite-page-title, td > code, th > code"));
"docs"===document.body.getAttribute("layout")&&a.v&&(b=Array.from(a.v.querySelectorAll("h1, h2, h3, h4, h5, h6")),c.push(...b));a.j.clear();a.j=new Set(c);if(_ds.F().hash){c=new _ds.oH;for(const d of a.j)_ds.nH(c,d,vU)}else GU(a,a.j);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))},FU=function(a){Array.from(a.getElementsByTagName("table")).forEach(b=>{if(!b.parentNode.classList.contains("devsite-table-wrapper")){var c=document.createElement("div");c.classList.add("devsite-table-wrapper");
b.classList.contains("full-width")&&(c.classList.add("devsite-full-width-table"),b.classList.remove("full-width"));_ds.ri(c,b);c.appendChild(b)}})},wU=async function(a,b){const c=IU(a,b.source);if(c){const e="goog_"+_ds.Yh++;c.setAttribute("name",e);var d=_ds.Zl(3);d=_ds.Kb(d,2,e);(b=b.source)&&b.postMessage(_ds.vf(d),"*");(b=document.body.getAttribute("appearance"))&&JU(c,b);a.C.push(c)}},xU=async function(a,b){const c=_ds.ji(document).y,d=_ds.mf(a,4);a=_ds.mf(a,3);b=_ds.zi(b);d&&b.setAttribute("width",
`${d}px`);a&&b.setAttribute("height",`${a}px`);window.requestAnimationFrame(()=>{window.scrollTo(_ds.ji(document).x,c)})},yU=async function(a,b,c){b=_ds.$l(_ds.Zl(8),_ds.x(b,8));c=_ds.Kb(b,6,c.toString());(a=a.source)&&a.postMessage(_ds.vf(c),"*")},zU=async function(a,b,c){b=_ds.$l(_ds.Zl(2),_ds.x(b,8));c=_ds.Kb(b,7,`${c.search}${c.hash}`);(a=a.source)&&a.postMessage(_ds.vf(c),"*")},AU=async function(a,b,c){const d=c.getTitle();b=new URL(c.getUrl(),b.origin);b=`${window.location.origin}${window.location.pathname}${b.search}${b.hash}`;
6===a?window.history.pushState({},d,b):window.history.replaceState({},d,b)},BU=async function(a,b){const c=_ds.x(b,9);let d;try{d=JSON.parse(_ds.x(b,10))}catch(e){console.warn("Event data from Framebox is not valid JSON.",a);return}"analyticsEvent"===c?a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:d,bubbles:!0})):"cloudtrackEvent"===c?a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:{eventData:d},bubbles:!0})):"devsite-apix"===c&&a.dispatchEvent(new CustomEvent("devsite-apix-observation",
{detail:d,bubbles:!0}))},CU=async function(a,b){if(a=a.getUrl()){const c=new URL(a,b.origin);a.startsWith("#")||b.origin===c.origin&&b.pathname===c.pathname&&b.search===c.search?DevsiteApp.scrollToAnchor(c.hash,!0):DevsiteApp.fetchPage(c.href)}},IU=function(a,b){let c;Array.from(a.querySelectorAll("devsite-iframe iframe")).forEach(d=>{_ds.Ai(d)===b&&(c=d)});return c},JU=function(a,b){var c=_ds.Zl(12);b=_ds.Kb(c,12,b);a&&a.contentWindow&&(a=a.contentWindow)&&a.postMessage(_ds.vf(b),"*")},EU=function(a){"full"===
document.body.getAttribute("layout")&&(a=a.v.querySelectorAll('h1[tabindex="0"],h2[tabindex="0"],h3[tabindex="0"],h4[tabindex="0"],h5[tabindex="0"],h6[tabindex="0"]'))&&Array.from(a).forEach(b=>{b.removeAttribute("tabindex")})},GU=function(a,b){a.h&&b.forEach(c=>{a.h.observe(c)})},KU=class extends _ds.E{constructor(){super();this.D=new _ds.G;this.F=new _ds.G;this.j=new Set;this.C=[];this.h=null;"IntersectionObserver"in window&&(this.h=new IntersectionObserver(a=>{for(const b of a)b.isIntersecting&&
(a=b.target,_ds.nH(new _ds.oH,a,vU),this.j.delete(a),this.h.unobserve(a))},{rootMargin:"100%"}))}connectedCallback(){this.D.listen(window,"message",a=>DU(this,a));this.D.listen(document.body,"devsite-appearance-updated",a=>{if((a=a.ma.detail.preference)&&this.C.length)for(const b of this.C)JU(b,a)});HU(this)}disconnectedCallback(){this.h&&this.h.disconnect();this.j.clear();_ds.H(this.D);_ds.H(this.F)}vb(a){a&&([".devsite-article",".devsite-content-data","devsite-content-footer","devsite-notification"].forEach(b=>
{_ds.th(this,this.querySelector(b),a.querySelector(b))}),HU(this))}};KU.prototype.updateContent=KU.prototype.vb;KU.prototype.disconnectedCallback=KU.prototype.disconnectedCallback;KU.prototype.connectedCallback=KU.prototype.connectedCallback;try{window.customElements.define("devsite-content",KU)}catch(a){console.warn("devsite.app.customElement.DevsiteContent",a)};})(_ds_www);
