(function(_ds){var window=this;var nY=function(a,b){b="translate3d("+b+"px,0px,0px)";_ds.il(a,mY(),b)},mY=_ds.Ch(function(){return _ds.qe&&9==_ds.Me?"-ms-transform":"transform"});var qY=function(a){a.j=oY(a,".devsite-top-logo-row-wrapper-wrapper");a.h=oY(a,".devsite-collapsible-section");a.v=oY(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",`${a.j}`);a.setAttribute("bottom-row--height",`${a.h}`);a.setAttribute("bottom-tabs--height",`${a.v}`);pY(a)},pY=function(a){const b=a.querySelector(".devsite-collapsible-section");a.offset>=a.h&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<a.h-a.v&&a.hasAttribute("bottom-row--hidden")&&
a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.G&&(_ds.il(b,"transform",`translate3d(0, -${a.offset}px, 0)`),rY(a),a.G=a.offset);document.body.style.setProperty("--devsite-js-header-height",`${a.C()}px`)},sY=function(a){var b=a.querySelector(".devsite-top-logo-row-middle");const c=a.querySelector("devsite-search"),d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.H(a.H);a.D&&window.cancelAnimationFrame(a.D);c.removeAttribute("transition");a.removeAttribute("search-expanded");
var e=new _ds.Ph(b.offsetWidth,b.offsetHeight);b=new _ds.Ph(c.offsetWidth,c.offsetHeight);var f=_ds.Bl(c),g="rtl"===document.documentElement.getAttribute("dir")?1:-1,h=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*g;var k=(f=a.hasAttribute("search-active"))?e:0,l=f?h:1;_ds.il(d,{opacity:1,width:`${b.width}px`,height:`${b.height}px`});nY(c,a.hasAttribute("search-active")?0:e);_ds.cl(a.H,d,_ds.Gf,()=>{const m=a.querySelector("devsite-search"),n=a.querySelector(".devsite-search-background");
n&&(n.style.opacity="0");m&&(m.removeAttribute("transition"),nY(m,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.D=window.requestAnimationFrame(()=>{c.setAttribute("transition","");var m="scale3d("+l+",1,1)";_ds.il(d,mY(),m);nY(c,k)})}},tY=async function(a,b){if(a.hasAttribute("billboard")){var c=a.querySelector("devsite-search"),d=a.querySelector("devsite-search input.devsite-search-query");a=a.querySelector(".devsite-header-billboard-search devsite-search");
var e=null==a?void 0:a.querySelector("input.devsite-search-query");c&&d&&a&&e&&(b?(c.removeAttribute("disabled"),document.activeElement===e&&(await _ds.Mj(),d.focus()),a.setAttribute("disabled","")):(a.removeAttribute("disabled"),document.activeElement===d&&e.focus(),c.setAttribute("disabled","")))}},vY=function(a){a.eventHandler.listen(a,"devsite-search-toggle",b=>{b=b.ma;_ds.Ki(b.target,null,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});
a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>document.body.removeAttribute("devsite-book-nav--open"));a.eventHandler.listen(window,"resize",()=>uY(a));a.eventHandler.listen(document.body,["devsite-page-loaded","devsite-content-updated"],()=>{uY(a)});a.eventHandler.listen(a,"click",b=>{b.defaultPrevented||"devsite-hamburger-menu"!==b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",
{bubbles:!0})))})},wY=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){const b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity="1";a.appendChild(b)}},rY=function(a){0===a.h?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},uY=function(a){window.requestAnimationFrame(()=>
a.K.Aa())},oY=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},xY=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},yY=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.th(a,c,b))},zY=class extends _ds.E{constructor(){super(...arguments);this.eventHandler=new _ds.G;this.G=
-1;this.H=new _ds.G;this.D=0;this.F=new MutationObserver(()=>qY(this));this.K=new _ds.Zk(()=>{qY(this);rY(this)},15);this.authUser=void 0;this.offset=this.v=this.h=this.j=0;this.updated=!1}static get observedAttributes(){return["offset","search-active","bottom-row--hidden"]}attributeChangedCallback(a,b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;pY(this);break;case "search-active":sY(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),
c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),tY(this,a)}}connectedCallback(){vY(this);wY(this);rY(this);qY(this);this.F.observe(this,{childList:!0,subtree:!0});pY(this);const a=_ds.F();this.authUser=_ds.nj(_ds.oj(a.href),"authuser")}disconnectedCallback(){_ds.H(this.eventHandler);this.F.disconnect()}C(){return this.j+this.h-this.offset}J(){return this.j+this.h}vb(a){this.updated=!1;if(a){yY(this,a,".devsite-header-upper-tabs");
yY(this,a,".devsite-collapsible-section");yY(this,a,".devsite-product-name-wrapper");yY(this,a,"devsite-language-selector");yY(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&xY(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(xY(c,b),c=_ds.F(),c=_ds.nj(_ds.oj(c.href),"authuser"),c!==this.authUser&&(this.authUser=c,b.refresh()));_ds.th(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),
this.querySelector(".devsite-top-logo-row-middle"));_ds.th(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.updated&&a&&(_ds.qi(this),this.appendChild(a));wY(this);uY(this)}};try{window.customElements.define("devsite-header",zY)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
