(function(_ds){var window=this;var VR=function(){return(0,_ds.T)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},WR=function(){return(0,_ds.T)('<div class="devsite-book-nav-blur"></div>')},YR=function(a){a=a.Hr;a=_ds.zz(new _ds.vz("{NUMBER_OF_MATCHING_DESCENDANTS,plural, =1{{XXX_1} coincidencia}other{{XXX_2} coincidencias}}"),{NUMBER_OF_MATCHING_DESCENDANTS:a,XXX_1:_ds.U(_ds.Xp(1)),XXX_2:_ds.U(_ds.Xp(a))});return(0,_ds.T)('<span class="devsite-nav-filter-match-count"> (<mark>'+
a+"</mark>)</span>")};var ZR="onpointerover"in window?"pointerover":"mouseover",$R=function(a){const b=0<a.querySelectorAll(".devsite-nav-item").length,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.C(a,"visually-hidden","",c))},hS=function(a){a.eventHandler.listen(a,"click",b=>void aS(a,b));a.eventHandler.listen(a,"keypress",b=>{13===b.keyCode&&aS(a,b)});a.eventHandler.listen(a,[ZR,"focusin"],b=>void bS(a,b));a.eventHandler.listen(document.body,"devsite-sitemask-hidden",
()=>{a.j&&(cS(a,"_book")?a.removeAttribute("top-level-nav"):_ds.C(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",()=>void a.J.Aa());a.eventHandler.listen(a,"devsite-content-updated",()=>{a.J.Aa()});a.eventHandler.listen(a,"scroll",()=>{_ds.C(a,"user-scrolled","")});a.eventHandler.listen(a.ub,"click",()=>{dS(a)});a.h&&(a.eventHandler.listen(a.h,"keyup",()=>void a.O.Aa()),a.eventHandler.listen(a.h,"focus",()=>void eS(a,"focus")));a.F&&a.eventHandler.listen(a.F,["click",
"keydown"],b=>{if("click"===b.type||13===b.keyCode||27===b.keyCode){a.h&&(a.h.value="",a.h.focus());let c;null==(c=a.F)||c.classList.add("hidden");fS(a);gS(a);eS(a,b.type)}})},jS=function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.D=new Set(b);if(!_ds.F().hash&&c)iS(a,a.D);else{c=new _ds.oH;for(const d of a.D)_ds.nH(c,d)}},kS=async function(a){const b=await _ds.v();for(const c of a.D)b.unregisterIntersectionForElement(c)},aS=function(a,b){if(!b.defaultPrevented){var c=b.target;
"devsite-close-nav"===c.getAttribute("id")&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.C(a,"top-level-nav",""));if(c.hasAttribute("menu")){var d=c.getAttribute("menu");d&&cS(a,d)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}var e=c.closest(".devsite-expandable-nav");if(e&&(d=c.closest(".devsite-nav-title, .devsite-nav-toggle"))){let f=
b.target,g,h;if(!(null==(g=f)?0:null==(h=g.closest(".devsite-nav-title"))?0:h.hasAttribute("href"))){for(b="click"===b.type||"touchend"===b.type;f&&f!==e;){if(f.classList.contains("devsite-nav-title-no-path")&&b){f.blur();break}f=f.parentNode}e.querySelector(".devsite-nav-section")&&(b=e.classList.toggle("expanded"),(e=e.querySelector(".devsite-nav-title"))&&_ds.C(a,"aria-expanded",`${b}`,e))}if(d.matches(".devsite-nav-toggle"))return}c.closest(".devsite-nav-title-no-path")||(a.j&&(d=a.j.querySelector("[menu=_book]"))&&
d.contains(c)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})),(c=c.closest("a.devsite-nav-title"))&&!c.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})))}},bS=function(a,b){b.defaultPrevented||(b=_ds.Ji(b.target,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0),b!==a&&_ds.Oc(b,_ds.ed(_ds.Fj(b.href).href)))},dS=async function(a){var b=document.documentElement.scrollHeight-document.documentElement.clientHeight;
const c=b?document.documentElement.scrollTop/b:0;_ds.cl(a.eventHandler,a,_ds.Gf,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.v.removeAttribute("animatable")});_ds.C(a,"animatable","");b=_ds.Sc(a.o`animatable`);b(a.background,"animatable","");b(a.v,"animatable","");a.hasAttribute("collapsed")?(_ds.C(a,"aria-expanded","true",a.ub),_ds.C(a,"aria-label","Ocultar men\u00fa de navegaci\u00f3n lateral",a.ub),_ds.C(a,"data-title","Ocultar men\u00fa de navegaci\u00f3n lateral",
a.ub),a.removeAttribute("collapsed"),lS(a,"Expanded book nav")):(a.ub.removeAttribute("aria-expanded"),_ds.C(a,"aria-label","Mostrar men\u00fa de navegaci\u00f3n lateral",a.ub),_ds.C(a,"data-title","Mostrar men\u00fa de navegaci\u00f3n lateral",a.ub),_ds.C(a,"collapsed",""),lS(a,"Collapsed book nav"));await _ds.Mj();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*b)},eS=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",
{detail:{category:"Site-Wide Custom Events",action:b,label:"focus"===b?"devsite-book-nav-filter input":"devsite-book-nav-filter filter-clear-button"},bubbles:!0}))},mS=function(a){a.G=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},oS=function(a){const b=_ds.F().searchParams.get("nf");a.h&&b&&(a.h.value=b,nS(a))},nS=function(a){if(a.G.length){fS(a);gS(a);var b,c,d=null==(b=a.h)?void 0:null==(c=b.value)?void 0:
c.trim().toLowerCase();if(d){var e;null==(e=a.F)||e.classList.remove("hidden");for(const g of a.G){c=g.querySelectorAll(".devsite-nav-text");b=g.classList.contains("devsite-nav-expandable");var f=e=!1;a=0;let h,k;if(d&&b&&(null==(h=g.querySelector(".devsite-nav-text"))?0:null==(k=h.textContent)?0:k.toLowerCase().includes(d)))f=e=!0;else for(const l of c){let m;d&&(null==(m=l.textContent)?0:m.toLowerCase().includes(d))&&(e=!0,++a)}if(!0===e){g.classList.remove("hidden");if(f){c=Array.from(g.querySelectorAll(".devsite-nav-item"));
for(const l of c){l.classList.remove("hidden");let m;d&&(null==(m=l.textContent)?0:m.toLowerCase().includes(d))&&++a}}c=void 0;(f=g.querySelector(".devsite-nav-text"))&&(e=null==(c=f.textContent)?void 0:c.replace(new RegExp(`(${d})`,"ig"),"<mark>$1</mark>"))&&_ds.Qc(f,_ds.rd.h(e))}b&&0<a&&(b=g.querySelector(".devsite-nav-text"))&&(a=_ds.N(YR,{Hr:a}),b.appendChild(a))}}else null==(f=a.F)||f.classList.add("hidden")}},fS=function(a){for(const b of a.G){let c;b.classList.toggle("hidden",!(null==(c=a.h)||
!c.value))}},gS=function(a){if(a.querySelector("mark")){var b=[...a.querySelectorAll(".devsite-nav-text > .devsite-nav-filter-match-count")];for(const c of b)c.remove();a=[...a.querySelectorAll(".devsite-nav-text > mark")];for(const c of a){a=c.parentElement;let d;b=null==(d=a)?void 0:d.textContent;a&&b&&_ds.Qc(a,_ds.rd.h(b))}}},iS=async function(a,b){if(a.C){var c=await _ds.v(),d=new _ds.oH,e=f=>{f=f.target;_ds.nH(d,f);a.D.delete(f);c.unregisterIntersectionForElement(f)};for(const f of b)try{c.registerIntersectionForElement(f,
e)}catch(g){e({target:f})}}},cS=function(a,b){let c=!1;if(a.j)for(const d of a.j.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),c=!0):_ds.C(a,"hidden","",d);return c},pS=function(a,b=a){b||(b=a);for(const c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active");a=_ds.Tj(_ds.F().pathname);a=`[href="${_ds.Fj(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(const c of b.querySelectorAll(a))c.classList.add("devsite-nav-active")},qS=function(a,b=a){b||(b=a);if(a=b.querySelector(".devsite-mobile-nav-bottom"))for(a=a.querySelector(".devsite-nav-active");a&&a.parentElement&&a.parentElement!==b;)a.matches(".devsite-expandable-nav:not(.expanded)")&&a.classList.add("expanded"),a=a.parentElement},sS=async function(a){a.C&&(a.removeAttribute("user-scrolled"),await _ds.Mj(),await rS(a),await a.V,await _ds.v(),await _ds.Mj(),await rS(a))},
rS=async function(a){if(a.C&&a.j){await _ds.v();var b=a.j.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await tS(a,b))}},tS=async function(a,b){if(a.C){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.sl(b,a,!0).y;await _ds.Mj();c&&_ds.C(a,"user-scrolled","")}},lS=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:"click",label:b},bubbles:!0}))},uS=class extends _ds.E{constructor(){super();
this.C=!1;this.F=this.h=this.H=this.j=null;this.G=[];this.eventHandler=new _ds.G;this.M=()=>{};this.D=new Set;this.K=this.W=!1;this.background=document.createElement("div");this.background.classList.add("devsite-book-nav-bg");this.ub=_ds.N(VR);this.v=_ds.N(WR);this.V=new Promise(a=>{this.M=a});this.J=new _ds.Zk(()=>{this.C&&$R(this)},20);this.O=new _ds.Zk(()=>{nS(this)},20)}static get observedAttributes(){return["collapsed","fixed","hidden"]}async connectedCallback(){this.C=!0;_ds.qh(this,this.o`animatable`,
this.o`aria-expanded`,this.o`aria-label`,this.o`collapsed`,this.o`data-title`,this.o`fixed`,this.o`has-book-nav`,this.o`hidden`,this.o`top-level-nav`,this.o`user-scrolled`,this.o`visually-hidden`);_ds.ri(this.background,this);this.hasAttribute("hidden")&&(_ds.C(this,"hidden","",this.ub),_ds.C(this,"hidden","",this.v));const a=await _ds.v();if(this.W=a.hasMendelFlagAccess("BookNav","enable_collapsible_book_nav")){let b;null==(b=this.parentElement)||b.insertBefore(this.ub,this.nextSibling);_ds.C(this,
"aria-label","Ocultar men\u00fa de navegaci\u00f3n lateral",this.ub);_ds.C(this,"data-title","Ocultar men\u00fa de navegaci\u00f3n lateral",this.ub);_ds.C(this,"aria-expanded","true",this.ub);let c;null==(c=this.parentElement)||c.insertBefore(this.v,this.nextSibling)}if(this.K=a.hasMendelFlagAccess("BookNav","enable_book_nav_filtering"))if(this.H=this.querySelector(".devsite-book-nav-filter"))this.h=this.H.querySelector("input[type=text]"),this.F=this.H.querySelector(".filter-clear-button"),mS(this),
oS(this);$R(this);hS(this);await this.init();jS(this)}disconnectedCallback(){this.C=!1;_ds.H(this.eventHandler);kS(this);this.D.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.C(this,"visually-hidden","",a);a=[this.background,this.ub,this.v];for(const b of a)b&&_ds.ti(b);this.removeAttribute("animatable");this.background.removeAttribute("animatable");this.v.removeAttribute("animatable");this.v.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){"hidden"===
a&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if("hidden"===a||"collapsed"===a){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.C(this,"has-book-nav","",b))}if("fixed"===a||"hidden"===a||"collapsed"===a){b=this.hasAttribute(a);const c=[this.background,this.ub,this.v];for(const d of c)d&&(b?_ds.C(this,a,"",
d):d.removeAttribute(a))}"fixed"===a&&this.M()}async init(a=!0){if(this.C){this.v.style.setProperty("--devsite-js-book-nav-scrollbar-width",`${this.offsetWidth-this.clientWidth}px`);this.j=this.querySelector(".devsite-mobile-nav-bottom");_ds.C(this,"top-level-nav","");this.j&&this.j.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");0===this.children.length&&_ds.C(this,"hidden","");if(this.background)for(const b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.C(this,
b,"",this.background);!this.hasAttribute("hidden")&&a?(pS(this),qS(this),await sS(this)):(await _ds.Mj(),await rS(this))}}async vb(a){a?(a=a.querySelector("nav")||null,pS(this,a),qS(this,a),a&&(await kS(this),this.D.clear(),jS(this,a,!1)),_ds.th(this,this.querySelector("nav"),a)):_ds.qi(this);if(this.K&&(mS(this),this.h)){this.h.value="";let b;null==(b=this.F)||b.classList.add("hidden");oS(this)}await _ds.Mj();await this.init(!1)}};uS.prototype.updateContent=uS.prototype.vb;
uS.prototype.attributeChangedCallback=uS.prototype.attributeChangedCallback;uS.prototype.disconnectedCallback=uS.prototype.disconnectedCallback;uS.prototype.connectedCallback=uS.prototype.connectedCallback;try{window.customElements.define("devsite-book-nav",uS)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
